services:
  mysql:
    image: mysql:8.0.41
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  user-management:
    image: user-management:latest
    container_name: user-management
    build:
      context: ./Backend/userManagement
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  product-catalog:
    image: product-catalog:latest
    container_name: product-catalog
    build:
      context: ./Backend/productCatalog
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "9001:9001"
    depends_on:
      - mysql

  epayment-cart:
    image: epayment-cart:latest
    container_name: epayment-cart
    build:
      context: ./Backend/epaymentCartService
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "9002:9002"
    depends_on:
      - mysql

  frontend:
    image: ecommerce-app:latest
    container_name: ecommerce-frontend
    build:
      context: ./Frontend/ecommerce-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - user-management
      - product-catalog
      - epayment-cart

volumes:
  mysql-data:
